name: Build Zui
description: Build Zui for the current platform
inputs:
  cmd:
    required: false
    default: yarn electron-builder
  gh_token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Build & Publish
      run: ${{ inputs.cmd }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh_token }}

    - name: Check notorization with gatekeeper
      if: runner.os == 'macOS'
      run: |
        spctl --assess --type execute --verbose --ignore-cache --no-cache dist/installers/mac/*.app
      shell: bash
