name: Create Release

on:
  workflow_dispatch:
  push:
    branches:
      - "release/**"

jobs:
  release:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Zui
        uses: actions/checkout@v3

      - name: Setup Zui
        uses: ./.github/actions/setup-zui

      - name: Build Zui
        uses: ./.github/actions/build-zui
        with:
          cmd: yarn electron-builder
          gh_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zui-installers
          path: dist/installers
